---
- name: Install Shadowsocks dependencies
  apt: pkg={{ item }}
  with_items: 
    - python-pip

- name: Install ShadowSocks
  pip: name=shadowsocks

- name: Generate ShadowSocks init script
  template: src=init.j2
            dest=/etc/init.d/shadowsocks
            owner=root
            group=root
            mode=755

- name: Generate ShadowSocks config file
  template: src=shadowsocks.json.j2
            dest="{{ shadowsocks_config_path }}"
            owner=root
            group=root
            mode=644
  notify: Restart ShadowSocks

- name: Generate ShadowSocks logrotate config file
  template: src=logrotate.j2
            dest=/etc/logrotate.d/shadowsocks
            owner=root
            group=root
            mode=644
